version: '3.8'

services:
  chat-app:
    build: .
    container_name: chat-app
    restart: always
    networks:
      - chat-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chat-app
    networks:
      - chat-network
    restart: always

networks:
  chat-network:
    driver: bridge
